version: 2.1

executors:
  default:
    docker:
      - image: google/cloud-sdk:312.0.0-alpine

commands:
  gloud_config:
    steps:
      - run:
          name: gcloud config
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}-a
            gcloud auth configure-docker --quiet --project ${GOOGLE_PROJECT_ID}
  docker_build:
    steps:
      - run:
          name: docker build
          command: |
            docker build . \
              -t ${GOOGLE_GCR_URL}/${GOOGLE_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}

jobs:
  test-and-push:
    executor:
      name: default
    steps:
      - setup_remote_docker
      - checkout
      - docker_build
      - run:
          name: test
          command: |
            docker run --rm -it \
              ${GOOGLE_GCR_URL}/${GOOGLE_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} \
              dnsmasq --test
      - gloud_config
      - run:
          name: docker push
          command: |
            docker push ${GOOGLE_GCR_URL}/${GOOGLE_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}

workflows:
  deploy:
    jobs:
      - test-and-push
